# Generated by Django 4.1.6 on 2023-03-13 09:46

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('diagram', models.ImageField(upload_to=students.models.profile_picture_dir, verbose_name='Diagram')),
            ],
            options={
                'verbose_name_plural': 'Logbook Entries',
            },
        ),
        migrations.CreateModel(
            name='ProgramDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Program Date',
            },
        ),
        migrations.CreateModel(
            name='WeekComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Industry Supervisor Comment')),
                ('school_comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='School Supervisor Comment')),
            ],
        ),
        migrations.CreateModel(
            name='WeekDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Week Dates',
            },
        ),
    ]
