# Generated by Django 4.1.6 on 2023-02-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiwesDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Program Date',
            },
        ),
        migrations.AlterModelOptions(
            name='logbookentry',
            options={'verbose_name_plural': 'Logbook Entries'},
        ),
        migrations.AlterModelOptions(
            name='weekdates',
            options={'verbose_name_plural': 'Week Dates'},
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student Id'),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.weekdates', verbose_name='Week Id'),
        ),
    ]
