# Generated by Django 4.1.6 on 2023-03-13 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekcomment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student Id'),
        ),
        migrations.AddField(
            model_name='weekcomment',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.weekdates', verbose_name='Week Id'),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student Id'),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.weekdates', verbose_name='Week Id'),
        ),
    ]
