# Generated by Django 4.1.6 on 2023-03-17 21:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='diagram',
            field=models.ImageField(upload_to=api.models.profile_picture_dir, verbose_name='Diagram'),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
