# Generated by Django 4.1.6 on 2023-02-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_siwesdate_programdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programdate',
            options={'verbose_name_plural': 'Program Date'},
        ),
        migrations.AlterField(
            model_name='weekdates',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weekdates',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
