# Generated by Django 4.1.6 on 2023-03-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_logbookentry_diagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='entry_date',
            field=models.DateTimeField(),
        ),
    ]
