# Generated by Django 4.1.6 on 2023-02-16 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_industry_based_supervisor_and_more'),
        ('api', '0004_alter_programdate_options_alter_weekdates_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student Id'),
        ),
    ]
