# Generated by Django 4.1.6 on 2023-03-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_logbookentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
