# Generated by Django 4.1.6 on 2023-03-24 08:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_logbookentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='diagram',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.profile_picture_dir, verbose_name='Diagram'),
        ),
    ]
