# Generated by Django 4.1.6 on 2023-02-16 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_placement_location'),
        ('api', '0005_alter_logbookentry_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdates',
            name='industry_comment',
        ),
        migrations.RemoveField(
            model_name='weekdates',
            name='school_comment',
        ),
        migrations.CreateModel(
            name='WeekComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_comment', models.CharField(max_length=1000, verbose_name='Industry Supervisor Comment')),
                ('school_comment', models.CharField(max_length=1000, verbose_name='School Supervisor Comment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student Id')),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.weekdates', verbose_name='Week Id')),
            ],
        ),
    ]
