# Generated by Django 4.1.6 on 2023-02-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_placement_location'),
        ('api', '0006_remove_weekdates_industry_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student Id'),
        ),
    ]
