# Generated by Django 4.1.6 on 2023-03-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_logbookentry_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekcomment',
            name='industry_comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Industry Supervisor Comment'),
        ),
        migrations.AlterField(
            model_name='weekcomment',
            name='school_comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='School Supervisor Comment'),
        ),
    ]
