# Generated by Django 4.1.6 on 2023-03-13 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('radius', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='IndustrySupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to=students.models.profile_picture_dir, verbose_name='profile picture')),
                ('phone_no', models.CharField(max_length=11)),
                ('placement_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='industry_based_supervisor.placementcentre', verbose_name='Placement Centre')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
