# Generated by Django 4.1.6 on 2023-03-14 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry_based_supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrysupervisor',
            name='placement_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='industry_based_supervisor.placementcentre', verbose_name='Placement Centre'),
        ),
    ]
