# Generated by Django 4.1.6 on 2023-02-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry_based_supervisor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrysupervisor',
            name='department_id',
        ),
        migrations.AlterField(
            model_name='industrysupervisor',
            name='placement_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='industry_based_supervisor.placementcentre', verbose_name='Placement Centre'),
        ),
    ]
