# Generated by Django 4.1.6 on 2023-03-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_industry_based_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='placement_location',
        ),
    ]
