# Generated by Django 4.1.6 on 2023-02-16 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry_based_supervisor', '0003_remove_industrysupervisor_department_id_and_more'),
        ('students', '0002_alter_student_industry_based_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='placement_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='industry_based_supervisor.placementcentre', verbose_name='Placement Location'),
        ),
    ]
